#Так обозначаются комментарии в bullwinkle
#Грамматика для синтаксического анализа списка имен

#Символы проверяются слева-направо
#Если первый встретившийся слева вариант подходит, 
#то он и используется

#Пробелы обязательны

#Правила вида <Rule> := <Rule> | <X>;
#Использовать нельзя из-за особенностей грамматики

#Поэтому используем "подсписок" в качестве звена между двумя
#уровнями списка

#Стартовый символ - первый символ (NameList)

<NameList> := <NameSubList> | <Name>;
<NameSubList> := <Name> <NameList>;

#Если символ описывается через регулярные выражения, то
#в bullwinkle он должен начинаться с символа начала строки "^"

#\u003b - только так можно обозначать ";" в bullwinkle

<Name> := ^[A-Z][a-z]+\u003b;

#Таким образом удается провести синтаксический анализ списка максимум
#из 20 имен. Для дальнейшего увеличения глубины необходимо описать
#NameSublist через варианты вроде следующих:
#<NameSubList>:= <Name> <Name> <Name> <Name> <Name> <NameList> | 
#<Name> <NameList>;
